<?php

date_default_timezone_set('UTC');

$OLD_PWD = $_SERVER['PWD'];

// work from lib directory
chdir(dirname($argv[0]));

if ($argv[0] === './pre-install.php' || $_SERVER['PWD'] !== $OLD_PWD) {
  // pwd doesn't resolve symlinks
  $LIB_DIR = $_SERVER['PWD'];
} else {
  // windows doesn't update $_SERVER['PWD']...
  $LIB_DIR = getcwd();
}
$APP_DIR = dirname($LIB_DIR);
$HTDOCS_DIR = $APP_DIR . '/htdocs';
$CONF_DIR = $APP_DIR . '/conf';

$HTTPD_CONF = $CONF_DIR . '/httpd.conf';
$CONFIG_FILE_INI = $CONF_DIR . '/config.ini';
$CONFIG_FILE_PHP = $CONF_DIR . '/config.inc.php';

chdir($LIB_DIR);

if (!is_dir($CONF_DIR)) {
  mkdir($CONF_DIR, 0755, true);
}

// check for non-interactive mode
define('NON_INTERACTIVE',
    isset($_SERVER['NON_INTERACTIVE'])
        ? $_SERVER['NON_INTERACTIVE'] === 'true'
        : false);


// configuration defaults
$DEFAULTS = array(
  'MOUNT_PATH' => '/ws/edge',
  'EDGE_WS_VERSION' => '0.1.0',
  'EDGE_HOST' => 'cwbpub.cr.usgs.gov',
  'EDGE_PORT' => '2060',
  'EDGE_TIMEOUT' => '5'
);
$HELP_TEXT = array(
  'MOUNT_PATH' => 'Url path to application',
  'EDGE_WS_VERSION' => 'Webservice api version',
  'EDGE_HOST' => 'EDGE server hostname or IP address',
  'EDGE_PORT' => 'EDGE server port',
  'EDGE_TIMEOUT' => 'EDGE server socket connect timeout in seconds'
);
// Interactively prompts user for config. Writes CONFIG_FILE_INI
include_once 'configure.inc.php';


// Parse the configuration
$CONFIG = parse_ini_file($CONFIG_FILE_INI);

// Write the HTTPD configuration file
file_put_contents($HTTPD_CONF, '
  ## autogenerated at ' . date('r') . '

  Alias ' . $CONFIG['MOUNT_PATH'] . ' ' . $HTDOCS_DIR . '

  RewriteEngine on
  RewriteRule ^' . $CONFIG['MOUNT_PATH'] . '/(index)\.(json)$ ' . $CONFIG['MOUNT_PATH'] . '/$1.php?format=$2 [L,PT,QSA]

  <Location ' . $CONFIG['MOUNT_PATH'] . '>
    Order allow,deny
    Allow from all

    <LimitExcept GET>
      deny from all
    </LimitExcept>

    AddCharset UTF-8 .json

    ExpiresActive on
    ExpiresDefault "access plus 1 days"
  </Location>
');
